# Generated by Django 3.2.15 on 2022-09-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discribtion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
