# Generated by Django 3.2.15 on 2022-09-23 06:09

from django.db import migrations, models
import tester.models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0004_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='', upload_to=tester.models.filepath),
        ),
    ]
