# Generated by Django 3.2.15 on 2022-09-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0006_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stream',
            field=models.CharField(default='', max_length=100),
        ),
    ]
